In [ ]:
import numpy as np


In [0]:
x=np.array([[2,55],[22,87],[34,90]])

In [0]:
x

array([[ 2, 55],
       [22, 87],
       [34, 90]])

In [0]:
x.shape

(3, 2)

In [0]:
y=x.reshape(2,3)

In [0]:
y

array([[ 2, 55, 22],
       [87, 34, 90]])

In [0]:
y[0:,1]

array([55, 34])

In [0]:
z=y[0:,1:]

In [0]:
z

array([[55, 22],
       [34, 90]])

In [0]:
zr=np.zeros((6,6))

In [0]:
zr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [0]:
np.ones((6,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [0]:
np.full((4,6),6)

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [0]:
np.ones((5,5),dtype='int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [0]:
x


array([[ 2, 55],
       [22, 87],
       [34, 90]])

In [0]:
y

array([[ 2, 55, 22],
       [87, 34, 90]])

In [0]:
x1=x*2

In [0]:
x1

array([[  4, 110],
       [ 44, 174],
       [ 68, 180]])

In [0]:
x+x1

array([[  6, 165],
       [ 66, 261],
       [102, 270]])

In [0]:
np.add(x,x1)

array([[  6, 165],
       [ 66, 261],
       [102, 270]])

In [0]:
x*x1

array([[    8,  6050],
       [  968, 15138],
       [ 2312, 16200]])